### ISSUE TITLE
Nuevo repositorio para la web

### ISSUE THREAD

**Issue by talueses** [Vuejs-lima/Vuejs-Lima#4]
¿Se debería de considerar un repositorio nuevo sólo para la web? Yo considero que sí. 
Y de ser así, hace falta migrar todo para allá. ¿Qué opinan @AKUmajinn @JoshDev1205 ?

**Comment by talueses** [comment]
Y el nombre para el repositorio, ¿Cuál sería?

**Comment by AKUmajinn** [comment]
I agree, con respecto al nombre no me parece relevante de discutir, algo genérico como "LandingLimaVuejs" estaría bien para mi

**Comment by JoshDev1205** [comment]
Claro la web puede estar en otro repositorio, no tendria problema.
Dependiendo de ello podemos asociarlo a Now

**Comment by talueses** [comment]
Genial. Entonces cierro el issue y procedo a crear un repositorio nuevo.
